import { describe, expect, it } from "vitest";
import type { MixParams, MortgageTrack } from "../contracts/mortgage";
import { calcRoute } from "./route";
import { calcMix } from "./mix";
import { mixRisk } from "./risk";

/**
 * Parity tests. Expected values were generated by running the EXACT functions
 * from the client's validated simulator (סימולטור_משכנתא.html) in Node — see the
 * throwaway oracle. The port must reproduce them.
 */

const params: MixParams = { "מדד": 0.03, "דולר": 0, "אירו": 0 };

/** Same arithmetic → expect (near-)identical doubles. */
function close(actual: number, expected: number, rel = 1e-9) {
  const tol = Math.max(Math.abs(expected) * rel, 1e-9);
  expect(Math.abs(actual - expected)).toBeLessThanOrEqual(tol);
}

describe("calcRoute — parity with simulator", () => {
  it("A: fixed unlinked (Shpitzer)", () => {
    const t: MortgageTrack = { kind: "fixed", amount: 100000, years: 20, board: "שפיצר", indexType: "ללא", indexPct: 0, anchor: 0.0462, margin: 0 };
    const c = calcRoute(t, params);
    expect(c.n).toBe(240);
    close(c.S, 639.1452207552255);
    close(c.T, 153394.85298125134);
    close(c.effRate, 0.04719094908516763);
    close(c.intr.reduce((s, v) => s + v, 0), 53394.85298125129);

    // independent closed-form Shpitzer check
    const r = 0.0462 / 12;
    const closedForm = (r * 100000) / (1 - Math.pow(1 + r, -240));
    close(c.S, closedForm);
  });

  it("B: fixed CPI-linked", () => {
    const t: MortgageTrack = { kind: "fixed", amount: 100000, years: 20, board: "שפיצר", indexType: "מדד", indexPct: 1, anchor: 0.0462, margin: 0 };
    const c = calcRoute(t, params);
    close(c.S, 639.1452207552255); // first payment same as unlinked
    close(c.T, 209832.65306699745);
    close(c.annualIndex, 0.03);
    close(c.intr.reduce((s, v) => s + v, 0), 66808.24004461164);
  });

  it("C: prime", () => {
    const t: MortgageTrack = { kind: "prime", amount: 100000, years: 25, board: "שפיצר", indexType: "ללא", indexPct: 0, anchor: 0.0456, margin: 0, changeMonths: 1 };
    const c = calcRoute(t, params);
    expect(c.n).toBe(300);
    close(c.S, 559.243576332364);
    close(c.T, 167773.07289970978);
  });

  it("D: equal principal (קרן שווה)", () => {
    const t: MortgageTrack = { kind: "fixed", amount: 100000, years: 20, board: "קרן שווה", indexType: "ללא", indexPct: 0, anchor: 0.0462, margin: 0 };
    const c = calcRoute(t, params);
    close(c.S, 801.6666666666666);
    close(c.T, 146392.49999999927);
    // first principal = E/n, first payment = E/n + E*r
    close(c.prin[1], 100000 / 240);
  });
});

const mix: MortgageTrack[] = [
  { kind: "fixed", amount: 170000, years: 20, board: "שפיצר", indexType: "ללא", indexPct: 0, anchor: 0.0462, margin: 0, sharePct: 17 },
  { kind: "fixed", amount: 170000, years: 20, board: "שפיצר", indexType: "מדד", indexPct: 1, anchor: 0.0462, margin: 0, sharePct: 17 },
  { kind: "variable", amount: 300000, years: 15, board: "שפיצר", indexType: "ללא", indexPct: 0, anchor: 0.047, margin: 0, sharePct: 30, changeMonths: 36 },
  { kind: "variable", amount: 150000, years: 15, board: "שפיצר", indexType: "מדד", indexPct: 1, anchor: 0.047, margin: 0, sharePct: 15, changeMonths: 60 },
  { kind: "prime", amount: 210000, years: 25, board: "שפיצר", indexType: "ללא", indexPct: 0, anchor: 0.0456, margin: 0, sharePct: 21, changeMonths: 1 },
];

describe("calcMix — parity with simulator (clock1-like, ₪1,000,000)", () => {
  it("aggregates match", () => {
    const m = calcMix(mix, params);
    close(m.E, 1000000);
    close(m.firstPay, 6836.149717150232);
    close(m.total, 1652389.886869939);
    close(m.interest, 535151.452617489);
    close(m.indexation, 117238.43425245001);
    close(m.avgRate, 0.046434);
    close(m.avgYears, 18.8);
    expect(m.maxN).toBe(300);
  });
});

describe("mixRisk — parity with simulator", () => {
  it("share-weighted score + label", () => {
    const r = mixRisk(mix);
    close(r.score, 2.6);
    expect(r.level).toBe(3);
    expect(r.label).toBe("בינונית");
  });

  it("empty mix is neutral", () => {
    expect(mixRisk([]).label).toBe("—");
  });
});
